artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "https://docs.google.com/spreadsheets/d/1odAmbaXp_Eh97s3yRnXWpg6KkXhX-j3r/edit?usp=sharing&ouid=117351143701340593072&rtpof=true&sd=true"
  local_data_file: artifacts/data_ingestion/data.xlsx

data_validation:
  isValid: False

data_processing:
  root_dir: artifacts/data_processing
  data_file: artifacts/data_ingestion/data.xlsx
  preprocessed_file: artifacts/data_processing/finalPreprocessed.csv

model_training:
  root_dir: artifacts/model_training
  data_file: artifacts/data_processing/finalPreprocessed.csv
  
model_validation:
  root_dir: artifacts/model_validation
  result_file: artifacts/model_validation/result.csv
  
best_model:
  root_dir: best_model
  model_path: best_model/model.dill